[package]
name = "libcontainer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = {version = "1.0"}
oci-spec = "0.7"
nix = {version = "0.29", features = ["process", "sched", "user", "hostname", "mount", "fs"]}
libc = "0.2"